import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Roboto, Poppins } from "next/font/google";
import { ThemeProvider } from "@mui/material/styles";
import { getLocale } from 'next-intl/server';

import theme from "../theme/theme";

import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: [ "300", "400", "500", "700"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  return (
    <html lang={locale} className={`${poppins.variable} ${roboto.variable}`}>
      <body className={`antialiased`}
      >
        { /* This is where the CSS variables are injected by MUI */}
        {/* enableCssLayer is a boolean that determines whether the CSS layer is enabled */}
        <AppRouterCacheProvider options={{ key: 'lu' }}>
          <ThemeProvider theme={theme}>
            <NextIntlClientProvider locale={locale}>
              {children}
            </NextIntlClientProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
