import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Roboto, Poppins } from "next/font/google";
import { ThemeProvider } from "@mui/material/styles";
import { getLocale } from 'next-intl/server';
import { notFound } from "next/navigation";

import theme from "../theme/theme";

import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: [ "300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getMessages(locale: string) {
  try {
    return (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    console.error(`Failed to load messages for locale: ${locale}`, error);
    return {};
  }
}



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages(locale);
  console.log('Current locale:', locale);
  console.log('Messages path:', `../messages/${locale}.json`);
  console.log('Messages loaded:', messages ? 'Yes' : 'No');
  console.log('Messages keys:', messages ? Object.keys(messages) : 'None');
  return (
    <html lang={locale} className={`${poppins.variable} ${roboto.variable}`}>
      <body className={`antialiased`}
      >
        { /* This is where the CSS variables are injected by MUI */}
        {/* enableCssLayer is a boolean that determines whether the CSS layer is enabled */}
        <AppRouterCacheProvider options={{ key: 'lu' }}>
          <ThemeProvider theme={theme}>
            <NextIntlClientProvider locale={locale} messages={messages}>
              {children}
            </NextIntlClientProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
